---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c=.yamllint", "."]
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.6.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
